# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clone:
    runs-on: ubuntu-latest
      steps:

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_TODEPLOY }}